version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r requirements.txt
      - pip install sonar-scanner-cli docker

  pre_build:
    commands:
      - echo "Rodando análise Sonar..."
      - : "${SONAR_PROJECT_KEY:?SONAR_PROJECT_KEY is required}"
      - : "${SONAR_ORGANIZATION:?SONAR_ORGANIZATION is required}"
      - : "${SONAR_TOKEN:?SONAR_TOKEN is required}"
      - sonar-scanner \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.organization=$SONAR_ORGANIZATION \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo "Build da imagem Docker"
      - docker build -t auraxis .

artifacts:
  files:
    - "**/*"
