#!/usr/bin/env bash
set -euo pipefail

SCHEMATHESIS_MAX_EXAMPLES="${SCHEMATHESIS_MAX_EXAMPLES:-5}"
HYPOTHESIS_SEED="${HYPOTHESIS_SEED:-20260220}"

echo "[schemathesis] max_examples=${SCHEMATHESIS_MAX_EXAMPLES} seed=${HYPOTHESIS_SEED}"

SCHEMATHESIS_MAX_EXAMPLES="${SCHEMATHESIS_MAX_EXAMPLES}" \
HYPOTHESIS_SEED="${HYPOTHESIS_SEED}" \
pytest -m schemathesis --maxfail=1
