"""Transaction OpenAPI metadata compatibility facade."""

from __future__ import annotations

from app.controllers.transaction.openapi import (
    CONTRACT_HEADER_PARAM,
    TRANSACTION_ACTIVE_LIST_DOC,
    TRANSACTION_CREATE_DOC,
    TRANSACTION_DASHBOARD_DOC,
    TRANSACTION_DELETED_LIST_DOC,
    TRANSACTION_EXPENSE_PERIOD_DOC,
    TRANSACTION_FORCE_DELETE_DOC,
    TRANSACTION_ID_PARAM,
    TRANSACTION_RESTORE_DOC,
    TRANSACTION_SOFT_DELETE_DOC,
    TRANSACTION_SUMMARY_DOC,
    TRANSACTION_UPDATE_DOC,
)

__all__ = [
    "CONTRACT_HEADER_PARAM",
    "TRANSACTION_ID_PARAM",
    "TRANSACTION_CREATE_DOC",
    "TRANSACTION_UPDATE_DOC",
    "TRANSACTION_SOFT_DELETE_DOC",
    "TRANSACTION_RESTORE_DOC",
    "TRANSACTION_DELETED_LIST_DOC",
    "TRANSACTION_ACTIVE_LIST_DOC",
    "TRANSACTION_SUMMARY_DOC",
    "TRANSACTION_DASHBOARD_DOC",
    "TRANSACTION_FORCE_DELETE_DOC",
    "TRANSACTION_EXPENSE_PERIOD_DOC",
]
